#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = process.cwd();
const packageJsonPath = resolve(repoRoot, "package.json");
const targetPath = resolve(repoRoot, "src/version.ts");

const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");

const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8"));
const packageVersion = packageJson.version;

if (typeof packageVersion !== "string" || packageVersion.trim() === "") {
  throw new Error("package.json version must be a non-empty string");
}

const next = `// AUTO-GENERATED by tools/sync-version.mjs\n// Canonical source: package.json \"version\"\n\n/**\n * Runtime engine version used for compatibility checks.\n *\n * Source of truth: package.json \"version\".\n */\nexport const ANANKE_ENGINE_VERSION = ${JSON.stringify(packageVersion)};\n`;

let prev = "";
try {
  prev = readFileSync(targetPath, "utf8");
} catch {
  // file may not exist yet
}

if (prev === next) {
  console.log(`Version sync OK: ${packageVersion}`);
  process.exit(0);
}

if (checkOnly) {
  console.error("Version sync check failed: src/version.ts is out of date.");
  console.error("Run: npm run sync-version");
  process.exit(1);
}

writeFileSync(targetPath, next, "utf8");
console.log(`Updated src/version.ts -> ${packageVersion}`);
