// src/taxation.ts — Phase 92: Taxation & Treasury Revenue
//
// Polities derive the bulk of their income from taxing population and trade.
// This module models per-capita tax yields by tech era, stability-modulated
// collection efficiency, and the unrest pressure that high rates generate.
//
// Design:
//   - Pure data layer — no Entity fields, no kernel changes.
//   - `TaxPolicy` is stored externally per polity by the host.
//   - Uses numeric TechEra values (0–8) from Phase-11 tech.ts.
//   - All arithmetic is integer fixed-point; no floating-point accumulation.
//   - Trade-route income (Phase-83/89) is separate and additive.
//
// Integration:
//   Phase 11 (Tech):    TechEra gates per-capita base yield.
//   Phase 61 (Polity):  population, stabilityQ, treasury_cu are read/mutated.
//   Phase 90 (Unrest):  computeTaxUnrestPressure returns a faminePressure_Q-style
//                       value for use as an additional unrest factor.

import { q, SCALE, clampQ, mulDiv } from "./units.js";
import type { Q }                   from "./units.js";
import type { Polity }              from "./polity.js";
import { TechEra }                  from "./sim/tech.js";

// ── Types ─────────────────────────────────────────────────────────────────────

/** Per-polity tax configuration. Store one externally per polity. */
export interface TaxPolicy {
  polityId: string;
  /**
   * Fraction of the theoretical maximum revenue to collect [0, SCALE.Q].
   * q(0.15) = standard rate; q(0.25) or above triggers unrest pressure.
   */
  taxRate_Q: Q;
  /**
   * Fraction of the population exempt from taxation (clergy, nobility, etc.)
   * [0, SCALE.Q].  Reduces taxable base proportionally.  Defaults to 0.
   */
  exemptFraction_Q?: Q;
}

/** Result returned by `stepTaxCollection`. */
export interface TaxCollectionResult {
  /** Cost-units added to polity treasury this step. */
  revenue_cu: number;
  /** Unrest pressure generated by the current tax rate [0, SCALE.Q]. */
  unrestPressure_Q: Q;
}

// ── Constants ─────────────────────────────────────────────────────────────────

/**
 * Annual tax revenue per capita at full (q(1.0)) tax rate, keyed by TechEra.
 * Prehistoric has no monetary economy — yield is zero.
 * Values are in cost-units per person per year.
 */
export const TAX_REVENUE_PER_CAPITA_ANNUAL: Record<number, number> = {
  [TechEra.Prehistoric]:  0,
  [TechEra.Ancient]:      2,
  [TechEra.Medieval]:     5,
  [TechEra.EarlyModern]: 15,
  [TechEra.Industrial]:  50,
  [TechEra.Modern]:     200,
  [TechEra.NearFuture]: 1_000,
  [TechEra.FarFuture]:  5_000,
  [TechEra.DeepSpace]:  20_000,
};

/**
 * Tax rate below which no unrest pressure is generated [Q].
 * Rates at or below this are considered politically acceptable.
 */
export const OPTIMAL_TAX_RATE_Q: Q = q(0.15);

/**
 * Tax rate above which unrest pressure reaches maximum [Q].
 * Between OPTIMAL and MAX, pressure scales linearly.
 */
export const MAX_TAX_RATE_Q: Q = q(0.50);

/**
 * Maximum unrest pressure that taxation alone can generate [Q].
 * Passed as an extra additive factor into Phase-90 `computeUnrestLevel`.
 */
export const MAX_TAX_UNREST_Q: Q = q(0.30);

// ── Factory ───────────────────────────────────────────────────────────────────

/** Create a default TaxPolicy with a standard rate and no exemptions. */
export function createTaxPolicy(polityId: string, taxRate_Q: Q = q(0.15) as Q): TaxPolicy {
  return { polityId, taxRate_Q };
}

// ── Core computation ──────────────────────────────────────────────────────────

/**
 * Compute annual tax revenue for a polity [cost-units/year].
 *
 * Formula:
 *   taxablePopulation = population × (SCALE.Q − exemptFraction) / SCALE.Q
 *   perCapita         = TAX_REVENUE_PER_CAPITA_ANNUAL[techEra]  (default 0)
 *   stabilityMul      = SCALE.Q/2 + mulDiv(SCALE.Q/2, stabilityQ, SCALE.Q)
 *                     ∈ [5000, 10000] = [q(0.50), q(1.00)]
 *   gross             = taxablePopulation × perCapita × taxRate / SCALE.Q
 *   annual            = round(gross × stabilityMul / SCALE.Q)
 *
 * Stability models collection efficiency: a fractured polity cannot collect
 * the full assessed tax.  At zero stability, only half the theoretical
 * revenue is gathered.
 */
export function computeAnnualTaxRevenue(polity: Polity, policy: TaxPolicy): number {
  const perCapita = TAX_REVENUE_PER_CAPITA_ANNUAL[polity.techEra] ?? 0;
  if (perCapita === 0) return 0;

  const exempt          = policy.exemptFraction_Q ?? (0 as Q);
  const taxablePop      = Math.round(polity.population * (SCALE.Q - exempt) / SCALE.Q);
  const gross           = Math.round(taxablePop * perCapita * policy.taxRate_Q / SCALE.Q);
  const stabilityMul    = SCALE.Q / 2 + mulDiv(SCALE.Q / 2, polity.stabilityQ, SCALE.Q);
  return Math.max(0, Math.round(gross * stabilityMul / SCALE.Q));
}

/**
 * Compute daily tax revenue [cost-units/day].
 * Derived from `computeAnnualTaxRevenue` with day-fraction rounding.
 */
export function computeDailyTaxRevenue(polity: Polity, policy: TaxPolicy): number {
  const annual = computeAnnualTaxRevenue(polity, policy);
  return Math.max(0, Math.round(annual / 365));
}

/**
 * Compute the unrest pressure generated by the current tax rate [Q].
 *
 * - At or below `OPTIMAL_TAX_RATE_Q`: pressure = 0.
 * - Between OPTIMAL and MAX_TAX_RATE_Q: linear ramp 0 → MAX_TAX_UNREST_Q.
 * - At or above MAX_TAX_RATE_Q: pressure = MAX_TAX_UNREST_Q.
 *
 * Pass the result as an extra additive unrest factor to Phase-90
 * `computeUnrestLevel`.
 */
export function computeTaxUnrestPressure(policy: TaxPolicy): Q {
  if (policy.taxRate_Q <= OPTIMAL_TAX_RATE_Q) return 0 as Q;
  const excess  = policy.taxRate_Q - OPTIMAL_TAX_RATE_Q;
  const range   = MAX_TAX_RATE_Q   - OPTIMAL_TAX_RATE_Q;
  const frac    = clampQ(Math.round(excess * SCALE.Q / range), 0, SCALE.Q);
  return clampQ(Math.round(frac * MAX_TAX_UNREST_Q / SCALE.Q), 0, MAX_TAX_UNREST_Q) as Q;
}

// ── Treasury step ─────────────────────────────────────────────────────────────

/**
 * Collect taxes for `elapsedDays` days and add to `polity.treasury_cu`.
 *
 * Mutates `polity.treasury_cu`.
 *
 * @returns Revenue added and the unrest pressure the current rate generates.
 */
export function stepTaxCollection(
  polity:      Polity,
  policy:      TaxPolicy,
  elapsedDays: number,
): TaxCollectionResult {
  const annual      = computeAnnualTaxRevenue(polity, policy);
  const revenue_cu  = Math.max(0, Math.round(annual * elapsedDays / 365));
  polity.treasury_cu += revenue_cu;
  const unrestPressure_Q = computeTaxUnrestPressure(policy);
  return { revenue_cu, unrestPressure_Q };
}

// ── Reporting ─────────────────────────────────────────────────────────────────

/**
 * Estimate how many days until the treasury reaches a target amount at the
 * current daily tax revenue.  Returns `Infinity` if daily revenue is zero.
 */
export function estimateDaysToTreasuryTarget(
  polity:        Polity,
  policy:        TaxPolicy,
  targetAmount:  number,
): number {
  const daily = computeDailyTaxRevenue(polity, policy);
  if (daily <= 0) return Infinity;
  const needed = Math.max(0, targetAmount - polity.treasury_cu);
  if (needed === 0) return 0;
  return Math.ceil(needed / daily);
}

/**
 * Compute the effective tax rate needed to hit a desired annual revenue,
 * clamped to [0, MAX_TAX_RATE_Q].
 *
 * Useful for host AI: "what rate do I need to fund X?"
 *
 * Returns MAX_TAX_RATE_Q if the desired revenue exceeds what full taxation
 * can provide.
 */
export function computeRequiredTaxRate(
  polity:         Polity,
  desiredAnnual:  number,
): Q {
  const perCapita = TAX_REVENUE_PER_CAPITA_ANNUAL[polity.techEra] ?? 0;
  if (perCapita === 0 || polity.population === 0) return MAX_TAX_RATE_Q;

  const stabilityMul = SCALE.Q / 2 + mulDiv(SCALE.Q / 2, polity.stabilityQ, SCALE.Q);
  // reverse-solve: rate = desiredAnnual × SCALE.Q² / (population × perCapita × stabilityMul)
  const numerator   = desiredAnnual * SCALE.Q * SCALE.Q;
  const denominator = polity.population * perCapita * stabilityMul;
  if (denominator <= 0) return MAX_TAX_RATE_Q;
  const rate = Math.ceil(numerator / denominator);
  return clampQ(rate, 0, MAX_TAX_RATE_Q) as Q;
}
