// AUTO-GENERATED by tools/sync-version.mjs
// Canonical source: package.json "version"

/**
 * Runtime engine version used for compatibility checks.
 *
 * Source of truth: package.json "version".
 */
export const ANANKE_ENGINE_VERSION = "0.4.0";
