/**
 * Phase 17: Historical weapons database
 * Spans six eras with realistic physical properties calibrated to archaeological and
 * biomechanics literature.  All units follow the project SI fixed-point conventions.
 */

import { q, to } from "./units.js";
import type { Weapon, RangedWeapon, WeaponDamageProfile } from "./equipment.js";

// ─── Shared damage profiles ────────────────────────────────────────────────────

const dmg = (
  surfF: number,
  intF: number,
  strF: number,
  bleed: number,
  pen: number,
): WeaponDamageProfile => ({
  surfaceFrac: q(surfF),
  internalFrac: q(intF),
  structuralFrac: q(strF),
  bleedFactor: q(bleed),
  penetrationBias: q(pen),
});

// Shared projectile profiles
const ARROW_DMG    = dmg(0.20, 0.65, 0.15, 0.90, 0.70);   // bodkin arrow
const BULLET_DMG   = dmg(0.20, 0.60, 0.20, 0.70, 0.65);   // generic bullet
const RIFLE_DMG    = dmg(0.15, 0.65, 0.20, 0.65, 0.75);   // jacketed rifle bullet
const THROWN_DMG   = dmg(0.30, 0.50, 0.20, 0.60, 0.45);   // thrown spear / javelin

// ─── PREHISTORIC MELEE ─────────────────────────────────────────────────────────

export const PREHISTORIC_MELEE: Weapon[] = [
  {
    id: "wpn_hand_axe",
    kind: "weapon",
    name: "Hand Axe",
    mass_kg: to.kg(0.50),
    bulk: q(1.0),
    reach_m: to.m(0.25),
    handedness: "oneHand",
    momentArm_m: to.m(0.18),
    readyTime_s: to.s(0.50),
    damage: dmg(0.55, 0.35, 0.10, 0.80, 0.15),
  },
  {
    id: "wpn_war_club",
    kind: "weapon",
    name: "War Club",
    mass_kg: to.kg(1.00),
    bulk: q(1.3),
    reach_m: to.m(0.55),
    handedness: "oneHand",
    momentArm_m: to.m(0.22),
    readyTime_s: to.s(0.55),
    damage: dmg(0.25, 0.25, 0.50, 0.15, 0.05),
  },
  {
    id: "wpn_flint_knife",
    kind: "weapon",
    name: "Flint Knife",
    mass_kg: to.kg(0.15),
    bulk: q(0.9),
    reach_m: to.m(0.18),
    handedness: "oneHand",
    momentArm_m: to.m(0.12),
    readyTime_s: to.s(0.30),
    damage: dmg(0.55, 0.35, 0.10, 0.85, 0.20),
  },
  {
    id: "wpn_flint_spear",
    kind: "weapon",
    name: "Flint-tipped Spear",
    mass_kg: to.kg(0.90),
    bulk: q(1.4),
    reach_m: to.m(1.90),
    handedness: "twoHand",
    momentArm_m: to.m(0.65),
    readyTime_s: to.s(0.45),
    damage: dmg(0.25, 0.60, 0.15, 0.65, 0.55),
  },
  {
    id: "wpn_bone_dagger",
    kind: "weapon",
    name: "Bone Dagger",
    mass_kg: to.kg(0.12),
    bulk: q(0.8),
    reach_m: to.m(0.15),
    handedness: "oneHand",
    momentArm_m: to.m(0.10),
    readyTime_s: to.s(0.28),
    damage: dmg(0.45, 0.40, 0.15, 0.70, 0.30),
  },
];

// ─── CLASSICAL MELEE ──────────────────────────────────────────────────────────

export const CLASSICAL_MELEE: Weapon[] = [
  {
    id: "wpn_pugio",
    kind: "weapon",
    name: "Pugio",
    mass_kg: to.kg(0.30),
    bulk: q(0.9),
    reach_m: to.m(0.22),
    handedness: "oneHand",
    momentArm_m: to.m(0.14),
    readyTime_s: to.s(0.32),
    damage: dmg(0.35, 0.50, 0.15, 0.75, 0.60),
  },
  {
    id: "wpn_gladius",
    kind: "weapon",
    name: "Gladius",
    mass_kg: to.kg(0.90),
    bulk: q(1.2),
    reach_m: to.m(0.55),
    handedness: "oneHand",
    momentArm_m: to.m(0.35),
    readyTime_s: to.s(0.48),
    damage: dmg(0.40, 0.45, 0.15, 0.70, 0.45),
  },
  {
    id: "wpn_xiphos",
    kind: "weapon",
    name: "Xiphos",
    mass_kg: to.kg(0.80),
    bulk: q(1.2),
    reach_m: to.m(0.62),
    handedness: "oneHand",
    momentArm_m: to.m(0.38),
    readyTime_s: to.s(0.50),
    damage: dmg(0.45, 0.40, 0.15, 0.70, 0.35),
  },
  {
    id: "wpn_kopis",
    kind: "weapon",
    name: "Kopis",
    mass_kg: to.kg(0.75),
    bulk: q(1.2),
    reach_m: to.m(0.62),
    handedness: "oneHand",
    momentArm_m: to.m(0.32),
    readyTime_s: to.s(0.52),
    damage: dmg(0.60, 0.30, 0.10, 0.75, 0.10),
  },
  {
    id: "wpn_spatha",
    kind: "weapon",
    name: "Spatha",
    mass_kg: to.kg(1.10),
    bulk: q(1.4),
    reach_m: to.m(0.90),
    handedness: "oneHand",
    momentArm_m: to.m(0.45),
    readyTime_s: to.s(0.58),
    damage: dmg(0.45, 0.40, 0.15, 0.65, 0.30),
  },
  {
    id: "wpn_dory",
    kind: "weapon",
    name: "Dory",
    mass_kg: to.kg(0.80),
    bulk: q(1.5),
    reach_m: to.m(2.20),
    handedness: "twoHand",
    momentArm_m: to.m(0.70),
    readyTime_s: to.s(0.45),
    damage: dmg(0.20, 0.65, 0.15, 0.60, 0.60),
  },
  {
    id: "wpn_sarissa",
    kind: "weapon",
    name: "Sarissa",
    mass_kg: to.kg(1.50),
    bulk: q(2.0),
    reach_m: to.m(5.50),
    handedness: "twoHand",
    momentArm_m: to.m(0.85),
    readyTime_s: to.s(0.90),
    damage: dmg(0.20, 0.65, 0.15, 0.55, 0.65),
  },
  {
    id: "wpn_pilum",
    kind: "weapon",
    name: "Pilum",
    mass_kg: to.kg(1.00),
    bulk: q(1.4),
    reach_m: to.m(0.45),
    handedness: "oneHand",
    momentArm_m: to.m(0.28),
    readyTime_s: to.s(0.55),
    damage: dmg(0.20, 0.65, 0.15, 0.55, 0.65),
  },
];

// ─── MEDIEVAL MELEE ───────────────────────────────────────────────────────────

export const MEDIEVAL_MELEE: Weapon[] = [
  {
    id: "wpn_arming_sword",
    kind: "weapon",
    name: "Arming Sword",
    mass_kg: to.kg(1.10),
    bulk: q(1.3),
    reach_m: to.m(0.85),
    handedness: "oneHand",
    momentArm_m: to.m(0.45),
    readyTime_s: to.s(0.50),
    damage: dmg(0.40, 0.45, 0.15, 0.65, 0.30),
  },
  {
    id: "wpn_dane_axe",
    kind: "weapon",
    name: "Dane Axe",
    mass_kg: to.kg(1.30),
    bulk: q(1.6),
    reach_m: to.m(1.15),
    handedness: "twoHand",
    momentArm_m: to.m(0.55),
    readyTime_s: to.s(0.65),
    damage: dmg(0.55, 0.30, 0.15, 0.75, 0.15),
  },
  {
    id: "wpn_battle_axe",
    kind: "weapon",
    name: "Battle Axe",
    mass_kg: to.kg(1.50),
    bulk: q(1.5),
    reach_m: to.m(0.65),
    handedness: "oneHand",
    momentArm_m: to.m(0.38),
    readyTime_s: to.s(0.60),
    damage: dmg(0.60, 0.25, 0.15, 0.70, 0.15),
  },
  {
    id: "wpn_flanged_mace",
    kind: "weapon",
    name: "Flanged Mace",
    mass_kg: to.kg(1.20),
    bulk: q(1.4),
    reach_m: to.m(0.58),
    handedness: "oneHand",
    momentArm_m: to.m(0.32),
    readyTime_s: to.s(0.55),
    damage: dmg(0.15, 0.30, 0.55, 0.10, 0.05),
  },
  {
    id: "wpn_war_flail",
    kind: "weapon",
    name: "War Flail",
    mass_kg: to.kg(1.50),
    bulk: q(1.6),
    reach_m: to.m(0.75),
    handedness: "oneHand",
    momentArm_m: to.m(0.35),
    readyTime_s: to.s(0.65),
    shieldBypassQ: q(0.55),
    damage: dmg(0.25, 0.35, 0.40, 0.20, 0.10),
  },
  {
    id: "wpn_morning_star",
    kind: "weapon",
    name: "Morning Star",
    mass_kg: to.kg(1.40),
    bulk: q(1.5),
    reach_m: to.m(0.62),
    handedness: "oneHand",
    momentArm_m: to.m(0.30),
    readyTime_s: to.s(0.60),
    shieldBypassQ: q(0.40),
    damage: dmg(0.25, 0.30, 0.45, 0.25, 0.20),
  },
  {
    id: "wpn_military_pick",
    kind: "weapon",
    name: "Military Pick",
    mass_kg: to.kg(1.30),
    bulk: q(1.4),
    reach_m: to.m(0.60),
    handedness: "oneHand",
    momentArm_m: to.m(0.32),
    readyTime_s: to.s(0.60),
    damage: dmg(0.10, 0.20, 0.70, 0.05, 0.70),
  },
  {
    id: "wpn_warhammer_med",
    kind: "weapon",
    name: "War Hammer",
    mass_kg: to.kg(1.50),
    bulk: q(1.5),
    reach_m: to.m(0.65),
    handedness: "oneHand",
    momentArm_m: to.m(0.35),
    readyTime_s: to.s(0.60),
    damage: dmg(0.10, 0.30, 0.60, 0.05, 0.05),
  },
  {
    id: "wpn_halberd",
    kind: "weapon",
    name: "Halberd",
    mass_kg: to.kg(2.50),
    bulk: q(2.0),
    reach_m: to.m(1.80),
    handedness: "twoHand",
    momentArm_m: to.m(0.70),
    readyTime_s: to.s(0.75),
    damage: dmg(0.45, 0.35, 0.20, 0.60, 0.35),
  },
  {
    id: "wpn_glaive",
    kind: "weapon",
    name: "Glaive",
    mass_kg: to.kg(2.00),
    bulk: q(1.9),
    reach_m: to.m(1.75),
    handedness: "twoHand",
    momentArm_m: to.m(0.65),
    readyTime_s: to.s(0.70),
    damage: dmg(0.60, 0.25, 0.15, 0.70, 0.10),
  },
  {
    id: "wpn_bastard_sword",
    kind: "weapon",
    name: "Bastard Sword",
    mass_kg: to.kg(1.60),
    bulk: q(1.6),
    reach_m: to.m(1.00),
    handedness: "oneHand",
    momentArm_m: to.m(0.50),
    readyTime_s: to.s(0.60),
    damage: dmg(0.40, 0.45, 0.15, 0.65, 0.35),
  },
  {
    id: "wpn_zweihander",
    kind: "weapon",
    name: "Zweihänder",
    mass_kg: to.kg(3.00),
    bulk: q(2.2),
    reach_m: to.m(1.45),
    handedness: "twoHand",
    momentArm_m: to.m(0.65),
    readyTime_s: to.s(0.85),
    damage: dmg(0.50, 0.30, 0.20, 0.65, 0.10),
  },
];

// ─── RENAISSANCE MELEE ────────────────────────────────────────────────────────

export const RENAISSANCE_MELEE: Weapon[] = [
  {
    id: "wpn_rapier",
    kind: "weapon",
    name: "Rapier",
    mass_kg: to.kg(1.00),
    bulk: q(1.2),
    reach_m: to.m(1.02),
    handedness: "oneHand",
    momentArm_m: to.m(0.48),
    readyTime_s: to.s(0.45),
    damage: dmg(0.15, 0.70, 0.15, 0.60, 0.80),
  },
  {
    id: "wpn_sidesword",
    kind: "weapon",
    name: "Sidesword",
    mass_kg: to.kg(1.20),
    bulk: q(1.3),
    reach_m: to.m(0.88),
    handedness: "oneHand",
    momentArm_m: to.m(0.44),
    readyTime_s: to.s(0.48),
    damage: dmg(0.35, 0.50, 0.15, 0.60, 0.45),
  },
  {
    id: "wpn_estoc",
    kind: "weapon",
    name: "Estoc",
    mass_kg: to.kg(1.40),
    bulk: q(1.4),
    reach_m: to.m(1.10),
    handedness: "oneHand",
    momentArm_m: to.m(0.50),
    readyTime_s: to.s(0.50),
    damage: dmg(0.05, 0.80, 0.15, 0.30, 0.95),
  },
  {
    id: "wpn_main_gauche",
    kind: "weapon",
    name: "Main Gauche",
    mass_kg: to.kg(0.35),
    bulk: q(0.9),
    reach_m: to.m(0.32),
    handedness: "oneHand",
    momentArm_m: to.m(0.18),
    readyTime_s: to.s(0.30),
    damage: dmg(0.20, 0.65, 0.15, 0.50, 0.50),
  },
  {
    id: "wpn_pike_ren",
    kind: "weapon",
    name: "Infantry Pike",
    mass_kg: to.kg(1.50),
    bulk: q(2.0),
    reach_m: to.m(4.50),
    handedness: "twoHand",
    momentArm_m: to.m(0.80),
    readyTime_s: to.s(0.85),
    damage: dmg(0.15, 0.70, 0.15, 0.50, 0.65),
  },
  {
    id: "wpn_poleaxe",
    kind: "weapon",
    name: "Poleaxe",
    mass_kg: to.kg(2.50),
    bulk: q(2.1),
    reach_m: to.m(1.75),
    handedness: "twoHand",
    momentArm_m: to.m(0.68),
    readyTime_s: to.s(0.75),
    damage: dmg(0.30, 0.35, 0.35, 0.45, 0.40),
  },
];

// ─── EARLY MODERN MELEE ───────────────────────────────────────────────────────

export const EARLY_MODERN_MELEE: Weapon[] = [
  {
    id: "wpn_cavalry_saber",
    kind: "weapon",
    name: "Cavalry Saber",
    mass_kg: to.kg(1.00),
    bulk: q(1.2),
    reach_m: to.m(0.90),
    handedness: "oneHand",
    momentArm_m: to.m(0.45),
    readyTime_s: to.s(0.48),
    damage: dmg(0.55, 0.35, 0.10, 0.75, 0.15),
  },
  {
    id: "wpn_smallsword",
    kind: "weapon",
    name: "Smallsword",
    mass_kg: to.kg(0.70),
    bulk: q(1.1),
    reach_m: to.m(0.90),
    handedness: "oneHand",
    momentArm_m: to.m(0.42),
    readyTime_s: to.s(0.40),
    damage: dmg(0.15, 0.70, 0.15, 0.55, 0.70),
  },
  {
    id: "wpn_socket_bayonet",
    kind: "weapon",
    name: "Socket Bayonet",
    mass_kg: to.kg(0.40),
    bulk: q(0.9),
    reach_m: to.m(0.28),
    handedness: "oneHand",
    momentArm_m: to.m(0.16),
    readyTime_s: to.s(0.35),
    damage: dmg(0.20, 0.65, 0.15, 0.60, 0.60),
  },
  {
    id: "wpn_entrenching_tool",
    kind: "weapon",
    name: "Entrenching Tool",
    mass_kg: to.kg(0.90),
    bulk: q(1.2),
    reach_m: to.m(0.38),
    handedness: "oneHand",
    momentArm_m: to.m(0.22),
    readyTime_s: to.s(0.45),
    damage: dmg(0.45, 0.30, 0.25, 0.45, 0.25),
  },
];

// ─── CONTEMPORARY MELEE ───────────────────────────────────────────────────────

export const CONTEMPORARY_MELEE: Weapon[] = [
  {
    id: "wpn_combat_knife",
    kind: "weapon",
    name: "Combat Knife",
    mass_kg: to.kg(0.30),
    bulk: q(0.9),
    reach_m: to.m(0.22),
    handedness: "oneHand",
    momentArm_m: to.m(0.14),
    readyTime_s: to.s(0.28),
    damage: dmg(0.30, 0.55, 0.15, 0.80, 0.65),
  },
  {
    id: "wpn_tactical_tomahawk",
    kind: "weapon",
    name: "Tactical Tomahawk",
    mass_kg: to.kg(0.70),
    bulk: q(1.1),
    reach_m: to.m(0.45),
    handedness: "oneHand",
    momentArm_m: to.m(0.28),
    readyTime_s: to.s(0.40),
    damage: dmg(0.55, 0.30, 0.15, 0.70, 0.20),
  },
  {
    id: "wpn_riot_baton",
    kind: "weapon",
    name: "Riot Baton",
    mass_kg: to.kg(0.80),
    bulk: q(1.1),
    reach_m: to.m(0.55),
    handedness: "oneHand",
    momentArm_m: to.m(0.30),
    readyTime_s: to.s(0.40),
    damage: dmg(0.20, 0.35, 0.45, 0.05, 0.05),
  },
];

// ─── PREHISTORIC RANGED ───────────────────────────────────────────────────────

export const PREHISTORIC_RANGED: RangedWeapon[] = [
  {
    id: "rng_atlatl_dart",
    kind: "ranged",
    name: "Atlatl Dart",
    category: "bow",
    mass_kg: to.kg(0.5),
    bulk: q(1.2),
    launchEnergy_J: 180,
    projectileMass_kg: to.kg(0.040),
    dragCoeff_perM: q(0.008),
    dispersionQ: q(0.014),
    recycleTime_s: to.s(3.0),
    damage: THROWN_DMG,
  },
  {
    id: "rng_simple_selfbow",
    kind: "ranged",
    name: "Simple Selfbow",
    category: "bow",
    mass_kg: to.kg(0.6),
    bulk: q(1.2),
    launchEnergy_J: 20,
    projectileMass_kg: to.kg(0.025),
    dragCoeff_perM: q(0.010),
    dispersionQ: q(0.018),
    recycleTime_s: to.s(2.5),
    damage: ARROW_DMG,
  },
];

// ─── CLASSICAL RANGED ─────────────────────────────────────────────────────────

export const CLASSICAL_RANGED: RangedWeapon[] = [
  {
    id: "rng_javelin_light",
    kind: "ranged",
    name: "Light Javelin",
    category: "thrown",
    mass_kg: to.kg(0.8),
    bulk: q(1.3),
    launchEnergy_J: 0,
    projectileMass_kg: to.kg(0.400),
    dragCoeff_perM: q(0.004),
    dispersionQ: q(0.016),
    recycleTime_s: to.s(4.0),
    damage: THROWN_DMG,
  },
  {
    id: "rng_pilum_throw",
    kind: "ranged",
    name: "Pilum (Thrown)",
    category: "thrown",
    mass_kg: to.kg(1.2),
    bulk: q(1.5),
    launchEnergy_J: 0,
    projectileMass_kg: to.kg(1.000),
    dragCoeff_perM: q(0.005),
    dispersionQ: q(0.020),
    recycleTime_s: to.s(5.0),
    damage: THROWN_DMG,
  },
  {
    id: "rng_composite_bow",
    kind: "ranged",
    name: "Composite Bow",
    category: "bow",
    mass_kg: to.kg(0.9),
    bulk: q(1.3),
    launchEnergy_J: 80,
    projectileMass_kg: to.kg(0.025),
    dragCoeff_perM: q(0.007),
    dispersionQ: q(0.010),
    recycleTime_s: to.s(1.8),
    damage: dmg(0.25, 0.60, 0.15, 0.80, 0.55),
  },
  {
    id: "rng_warbow",
    kind: "ranged",
    name: "English Warbow",
    category: "bow",
    mass_kg: to.kg(1.1),
    bulk: q(1.6),
    launchEnergy_J: 120,
    projectileMass_kg: to.kg(0.030),
    dragCoeff_perM: q(0.005),
    dispersionQ: q(0.008),
    recycleTime_s: to.s(2.2),
    damage: ARROW_DMG,
  },
];

// ─── MEDIEVAL RANGED ──────────────────────────────────────────────────────────

export const MEDIEVAL_RANGED: RangedWeapon[] = [
  {
    id: "rng_arbalest",
    kind: "ranged",
    name: "Arbalest",
    category: "bow",
    mass_kg: to.kg(5.0),
    bulk: q(2.2),
    launchEnergy_J: 350,
    projectileMass_kg: to.kg(0.045),
    dragCoeff_perM: q(0.004),
    dispersionQ: q(0.005),
    recycleTime_s: to.s(12.0),
    damage: dmg(0.15, 0.70, 0.15, 0.75, 0.80),
  },
  {
    id: "rng_hand_cannon",
    kind: "ranged",
    name: "Hand Cannon",
    category: "firearm",
    mass_kg: to.kg(3.5),
    bulk: q(2.0),
    launchEnergy_J: 300,
    projectileMass_kg: to.kg(0.030),
    dragCoeff_perM: q(0.003),
    dispersionQ: q(0.022),
    recycleTime_s: to.s(40.0),
    damage: dmg(0.25, 0.55, 0.20, 0.65, 0.55),
  },
  {
    id: "rng_arquebus",
    kind: "ranged",
    name: "Arquebus",
    category: "firearm",
    mass_kg: to.kg(4.5),
    bulk: q(2.2),
    launchEnergy_J: 250,
    projectileMass_kg: to.kg(0.028),
    dragCoeff_perM: q(0.003),
    dispersionQ: q(0.018),
    recycleTime_s: to.s(30.0),
    damage: dmg(0.25, 0.55, 0.20, 0.65, 0.55),
  },
];

// ─── RENAISSANCE RANGED ───────────────────────────────────────────────────────

export const RENAISSANCE_RANGED: RangedWeapon[] = [
  {
    id: "rng_wheellock_pistol",
    kind: "ranged",
    name: "Wheellock Pistol",
    category: "firearm",
    mass_kg: to.kg(1.8),
    bulk: q(1.5),
    launchEnergy_J: 250,
    projectileMass_kg: to.kg(0.015),
    dragCoeff_perM: q(0.003),
    dispersionQ: q(0.020),
    recycleTime_s: to.s(20.0),
    damage: BULLET_DMG,
  },
  {
    id: "rng_flintlock_rifle",
    kind: "ranged",
    name: "Flintlock Rifle",
    category: "firearm",
    mass_kg: to.kg(4.2),
    bulk: q(2.0),
    launchEnergy_J: 900,
    projectileMass_kg: to.kg(0.028),
    dragCoeff_perM: q(0.002),
    dispersionQ: q(0.008),
    recycleTime_s: to.s(20.0),
    damage: RIFLE_DMG,
  },
];

// ─── EARLY MODERN RANGED ──────────────────────────────────────────────────────

export const EARLY_MODERN_RANGED: RangedWeapon[] = [
  {
    id: "rng_percussion_rifle",
    kind: "ranged",
    name: "Percussion Rifle",
    category: "firearm",
    mass_kg: to.kg(4.0),
    bulk: q(2.0),
    launchEnergy_J: 1200,
    projectileMass_kg: to.kg(0.028),
    dragCoeff_perM: q(0.002),
    dispersionQ: q(0.006),
    recycleTime_s: to.s(12.0),
    damage: RIFLE_DMG,
  },
  {
    id: "rng_early_revolver",
    kind: "ranged",
    name: "Early Revolver",
    category: "firearm",
    mass_kg: to.kg(1.4),
    bulk: q(1.3),
    launchEnergy_J: 350,
    projectileMass_kg: to.kg(0.012),
    dragCoeff_perM: q(0.002),
    dispersionQ: q(0.015),
    recycleTime_s: to.s(20.0),
    magCapacity: 6,
    shotInterval_s: to.s(0.8),
    damage: BULLET_DMG,
  },
  {
    id: "rng_breech_rifle",
    kind: "ranged",
    name: "Breech-Loading Rifle",
    category: "firearm",
    mass_kg: to.kg(4.2),
    bulk: q(2.0),
    launchEnergy_J: 1400,
    projectileMass_kg: to.kg(0.028),
    dragCoeff_perM: q(0.002),
    dispersionQ: q(0.005),
    recycleTime_s: to.s(8.0),
    damage: RIFLE_DMG,
  },
  {
    id: "rng_handgun_9mm",
    kind: "ranged",
    name: "Handgun 9mm",
    category: "firearm",
    mass_kg: to.kg(0.8),
    bulk: q(1.1),
    launchEnergy_J: 520,
    projectileMass_kg: to.kg(0.008),
    dragCoeff_perM: q(0.002),
    dispersionQ: q(0.004),
    recycleTime_s: to.s(2.5),
    magCapacity: 15,
    shotInterval_s: to.s(0.2),
    damage: BULLET_DMG,
  },
];

// ─── CONTEMPORARY RANGED ─────────────────────────────────────────────────────

export const CONTEMPORARY_RANGED: RangedWeapon[] = [
  {
    id: "rng_assault_rifle",
    kind: "ranged",
    name: "Assault Rifle",
    category: "firearm",
    mass_kg: to.kg(3.5),
    bulk: q(1.8),
    launchEnergy_J: 1760,
    projectileMass_kg: to.kg(0.004),
    dragCoeff_perM: q(0.001),
    dispersionQ: q(0.003),
    recycleTime_s: to.s(3.0),
    magCapacity: 30,
    shotInterval_s: to.s(0.1),
    damage: dmg(0.10, 0.75, 0.15, 0.55, 0.85),
  },
  {
    id: "rng_battle_rifle",
    kind: "ranged",
    name: "Battle Rifle",
    category: "firearm",
    mass_kg: to.kg(4.3),
    bulk: q(1.9),
    launchEnergy_J: 3300,
    projectileMass_kg: to.kg(0.0097),
    dragCoeff_perM: q(0.001),
    dispersionQ: q(0.003),
    recycleTime_s: to.s(3.5),
    magCapacity: 20,
    shotInterval_s: to.s(0.2),
    damage: dmg(0.10, 0.75, 0.15, 0.50, 0.85),
  },
  {
    id: "rng_sniper_rifle",
    kind: "ranged",
    name: "Sniper Rifle",
    category: "firearm",
    mass_kg: to.kg(6.5),
    bulk: q(2.2),
    launchEnergy_J: 3300,
    projectileMass_kg: to.kg(0.0097),
    dragCoeff_perM: q(0.001),
    dispersionQ: q(0.002),
    recycleTime_s: to.s(8.0),
    magCapacity: 10,
    shotInterval_s: to.s(2.5),
    damage: dmg(0.05, 0.80, 0.15, 0.40, 0.90),
  },
  {
    id: "rng_shotgun_12g",
    kind: "ranged",
    name: "Shotgun 12-Gauge",
    category: "firearm",
    mass_kg: to.kg(3.4),
    bulk: q(1.8),
    launchEnergy_J: 1800,
    projectileMass_kg: to.kg(0.032),
    dragCoeff_perM: q(0.003),
    dispersionQ: q(0.035),
    recycleTime_s: to.s(8.0),
    magCapacity: 6,
    shotInterval_s: to.s(0.5),
    damage: dmg(0.65, 0.25, 0.10, 0.80, 0.05),
  },
  {
    id: "rng_submachine_gun",
    kind: "ranged",
    name: "Submachine Gun",
    category: "firearm",
    mass_kg: to.kg(2.8),
    bulk: q(1.5),
    launchEnergy_J: 520,
    projectileMass_kg: to.kg(0.008),
    dragCoeff_perM: q(0.002),
    dispersionQ: q(0.007),
    recycleTime_s: to.s(2.5),
    magCapacity: 30,
    shotInterval_s: to.s(0.1),
    damage: dmg(0.25, 0.60, 0.15, 0.65, 0.55),
  },
];

// ─── Aggregate exports ────────────────────────────────────────────────────────

export const ALL_HISTORICAL_MELEE: Weapon[] = [
  ...PREHISTORIC_MELEE,
  ...CLASSICAL_MELEE,
  ...MEDIEVAL_MELEE,
  ...RENAISSANCE_MELEE,
  ...EARLY_MODERN_MELEE,
  ...CONTEMPORARY_MELEE,
];

export const ALL_HISTORICAL_RANGED: RangedWeapon[] = [
  ...PREHISTORIC_RANGED,
  ...CLASSICAL_RANGED,
  ...MEDIEVAL_RANGED,
  ...RENAISSANCE_RANGED,
  ...EARLY_MODERN_RANGED,
  ...CONTEMPORARY_RANGED,
];
